name: Test Install

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Test install script
        run: ./install.sh

  test-nixos:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
      volumes:
        - /nix:/nix
      options: --privileged
    steps:
      - name: Install System Dependencies
        run: |
          # Install basic utilities that might be missing
          nix-env -iA nixpkgs.coreutils nixpkgs.sudo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: false
          clean: false
      - name: Generate NixOS Configuration
        run: sudo nixos-generate-config
      - name: Test install script
        run: |
          chmod +x install.sh
          ./install.sh
