name: Test Install

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Token
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Make install script executable
        run: chmod +x install.sh

      - name: Run install script
        run: ./install.sh
