name: Test Install

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Test install script
        run: ./install.sh

  test-nixos:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Test install script
        run: ./install.sh
