name: Test Install

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Test install script
        run: ./install.sh

  test-nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start NixOS Container
        run: |
          docker run -d --name nixos \
            --privileged \
            -v ${{ github.workspace }}:/workspace \
            -v /nix:/nix \
            nixos/nix:latest \
            /bin/sh -c "while true; do sleep 30; done"
      - name: Install Dependencies
        run: |
          docker exec nixos nix-env -iA nixpkgs.busybox nixpkgs.sudo
      - name: Generate NixOS Config
        run: |
          docker exec nixos sudo nixos-generate-config
      - name: Test Install Script
        run: |
          docker exec nixos chmod +x /workspace/install.sh
          docker exec nixos /workspace/install.sh
