name: Test Install

on: [push]

jobs:
 test-macos:
   runs-on: macos-latest
   timeout-minutes: 30
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up GitHub Token
       run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

     - name: Run install script
       run: curl -fsSL https://darwin.aloshy.ai | bash
